### ISSUE TITLE
ROOT_URL is not supported

### ISSUE THREAD

**Issue by lc3t35** [msavin/MeteorCandy-meteor-admin#7]
After CtrlD it fails to grab users and run functions server commands when I launch with : 
````
ROOT_URL=http://192.168.1.x:3000/ meteor --settings settings-development.json 
````
In this case page is at http://192.168.1.x:3000/
If I launch with 
````
meteor --settings settings-development.json 
````
Page is on localhost:3000 -> users and functions ok

**Comment by msavin** [comment]
Are you running the business or developer edition? It could be that the developer edition only supports `localhost:3000`

**Comment by lc3t35** [comment]
developer as I'm just testing -> is it possible to support ROOT_URL ?

**Comment by msavin** [comment]
I'm not sure how you are using it, but maybe this workaround can get you through:

```
if (Meteor.isDevelopment) {
  return "localhost:3000"
} else {
  return ROOT_URL
}
```

How is your experience with the package otherwise?
