### ISSUE TITLE
Business Edition: TypeError: api.toggle is not a function

### ISSUE THREAD

**Issue by all9lives** [msavin/MeteorCandy-meteor-admin#8]
I'm having some issues getting meteor candy business edition to work in development. I tried the development version, everything worked great, even created some custom actions etc in the config package. Now when installing the business edition (I purchased the react version) I'm getting the following error when pressing control+d. 

Uncaught (in promise) TypeError: api.toggle is not a function

![jtly-kin1 2018-04-27 17-38-40](https://user-images.githubusercontent.com/1470953/39554080-ad5e429a-4e25-11e8-8853-8fc4ec8e8ed7.png)

* I'm using Meteor 1.6.1.1, React 15.6
* If it matters I'm also using meteor-toys,

p.s. I also emailed you 5 days ago requesting support for this paid product but I'm yet to get any response. Not very encouraging since the Meteor Candy website lists email support as one of the business edition features.

**Comment by msavin** [comment]
My apologies for the slow response. I sent you an email recently but thought it might help to bring the discussion here.

This looks like an unusual issue. Have you removed `meteorcandy:core`, and is `meteor-candy-config` loading before `meteor-candy`?

If that doesn't help, can you send your package list?

**Comment by msavin** [comment]
@all9lives thanks for the info - glad you found it helpful -  React has not been forgotten :D
